### ISSUE TITLE
bill 新增「議案資料」頁面

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly-v2#12]
bill 新增一個「議案資料」的 item_feature 頁面，裡頭呈現的資料跟排列方式請參照 ppg 的議案頁面

本頁面大概有這幾項大項
- 基本資料：議案的類別、名稱、來源、狀態..etc
- 議案流程
- 關連議案 - 立法院議事暨公報資訊網版
- 關連議案 - OpenFun 版

**Comment by typingmonk** [comment]
Done 已部署到測試環境，麻煩 @ronnywang 測試檢查

**Comment by Legendream** [comment]
@typingmonk 例會上，是討論議案分成兩個 tab，一個是議案的基本資訊；另一個是關聯議案的檔案做成網頁版。
想請問是不是就是這 issue 你說的「關連議案 - 立法院議事暨公報資訊網版」？
是的話，是不是要另開一個 issue 啊？

**Comment by typingmonk** [comment]
例會說要拆成兩個 tab 的兩個資料是「議案資料」「關係文書」
然後現在在這頁裡頭有兩個版本的「關連議案」是在開發過程中發現，如同例會中說明的，有兩個關連的邏輯，所以想說乾脆在這頁把兩種關連的版本都呈現出來

**Comment by Legendream** [comment]
我確認一下意思，這是指「議案資料」的 tab 會呈現關聯的邏輯；我們還是需要第二個 tab 呈現「關係文書」的內容在網頁上，對嗎？

**Comment by typingmonk** [comment]
![image](https://github.com/user-attachments/assets/17d7564c-0230-4e9f-b773-f0ced6238b97)

#### Tab 議案資料
裡頭有呈現跟這個議案有關連的其他議案，稱作「關連議案」，關連的方式有兩種版本，ppg 的跟 openfun 的版本

#### Tab 關係文書
關係文書是一種公文的名稱，每一個議案應該至少要有一份關係文書，在 ppg 上都是提供 PDF 檔案要使用者自己打開來看
這邊把公文的內容放在這個 Tab 中呈現
如果這個議案是「法律案」，裡頭就可能會有法律對照表，這個議案的法律對照表就可以在這個 tab 瀏覽

**Comment by ronnywang** [comment]
現在「議案資料」等於是 https://ppg.ly.gov.tw/ppg/bills/202110002460000/details 這一頁資料的呈現再加上 openfun 自己的關聯議案
而「關係文書」則是裡面的 Word 的內容

我覺得目前議案資料這樣做很好，這個 #12 issue 我覺得可以先推上線
衍生還可以做的包含：
1. 議案流程　那邊，包含原始的大公報網裡面，都只有很粗略寫到「社會福利及衛生環境委員會」，可以之後讓他直接連到「會議」的頁面（現在還沒有會議的頁面）

其他部份我們可以留待每週例會討論之後的延伸

這部份也請 claire 確認看看目前這個 issue 的進度，沒問題就給 tmonk 推上線吧

**Comment by Legendream** [comment]
我覺得很棒！有一點我不確定要另開 issue or 算這張 issue
關連議案 - OpenFun 版 --> 似乎可以解釋一下這個跟「關連議案 - 立法院議事暨公報資訊網版」的差別是什麼，使用者才會知道

**Comment by typingmonk** [comment]
大原則是盡量拆 issue，這樣的話就能 [release fast, release often](https://en.wikipedia.org/wiki/Release_early,_release_often)
網站的確有不少欄位是需要額外說明的，但如果直接把說明放在欄位旁邊大概都會破壞版型，之後這類的說明建議可以寫在 hackmd 裡頭，然後用 hackmd book 收錄，網站只需要提供一個 icon 給使用者連過去就好

沒有其他問題，接下來會推上線

**Comment by typingmonk** [comment]
已推上線
Issue close
