### ISSUE TITLE
legislator 新增「立委資料」頁面

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly-v2#13]
legislator 新增一個「立委資料」的 item_feature 頁面，裡頭呈現的資料跟排列方式請參照立法院官網的立委頁面，以及這週開會畫的 wireframe

**Comment by Legendream** [comment]
補充會議上討論的紀錄
- 立委選區：連結到維基百科，以解決每一屆選區劃分可能會變化的問題
- 立委辦公室的電話：欄位留空，寫類似「未來補上開放資料」之類的。我想問：如果連到立院的頁面，如何？
- 就任日期：先按照立委網站呈現的方式，未來再看要不要、怎麼調整

**Comment by typingmonk** [comment]
Done 已部署到測試環境，請 @ronnywang 跟 @Legendream 測試確認

**Comment by Legendream** [comment]
我覺得很棒！等 Ronny 確認完就可以 close the issue 了

**Comment by typingmonk** [comment]
補充說明：
- 立委選區都有直接連到該選舉區的維基百科頁面
- 立委聯絡資訊：因為目前 API 沒有收錄立院官網立法委員頁面的 url，所以目前每一個連結都是連到立院官網的立委查詢頁面

**Comment by ronnywang** [comment]
ok 喔，讚讚， tmonk 把他推上線吧

**Comment by typingmonk** [comment]
已推上線
Issue close
