### ISSUE TITLE
gazette 新增「公報資料」頁面

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly-v2#18]
參考 ppg 的公報頁面呈現跟公報相關的資料

**Comment by typingmonk** [comment]
已完成，除了呈現 API 中公報的基本資料，還有 table 呈現所有關連到的公報章節並提供連結
麻煩 @ronnywang 確認複查

**Comment by ronnywang** [comment]
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/2054ad2b-266c-4a97-b4d3-c66af9157563">
可以讓案由那邊會往下換行嗎？覺得需要往右捲才可以看內容不是很方便
把他改成會自動往下換行應該會比較好閱讀？

其他部份我就沒什麼問題了

**Comment by typingmonk** [comment]
已改變 table CSS 樣式，讓它會向下換行而不是要左右 scroll

![image](https://github.com/user-attachments/assets/3b54d03c-7c09-4103-a943-913428fc9d0b)

**Comment by ronnywang** [comment]
好，沒問題，那就先推上線吧，至於其他美觀問題就之後再開 issue 調整吧
