### ISSUE TITLE
gazette_agenda 新增「公報章節資料」頁面

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly-v2#19]
公報章節的資料原始來源是 doc/pdf 檔案，直接把透過 doc 轉成的 html 放在這頁上

**Comment by typingmonk** [comment]
已完成，除了呈現公報章節的基本資料外，還有透過 tikahtml 的資料在這頁呈現章節內容
麻煩 @ronnywang 確認複查

**Comment by ronnywang** [comment]
章節內容可以另外分一個分頁出來嗎？把資訊(用table呈現的）和內容（pdf to html) 分成兩個 tab 來顯示
就不會讓資訊這一頁的內容過多

其他部份我沒問題

**Comment by typingmonk** [comment]
新增一個 tab: 章節內容把 html_content 改在這個 tab 呈現
已推上線
Issue close
