### ISSUE TITLE
dataly-old-v1:ivod list 搬移到 dataly-v2

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly-v2#22]
如題，把舊版的 ivod list 搬移到 dataly-v2，列表樣式如下圖
舊版 ivod list 連結：https://dataly-old-v1.openfun.app/ivod

**Comment by typingmonk** [comment]
已完成

新增一個 ivod 的 collection_feature: `datelist`
根據 GET 的參數， datelist 會有兩種不同的清單

`?日期=YYYY-MM-DD`
如果在參數上提供符合上述格式日期，會呈現該天所有的 ivod 列表，呈現的樣式跟舊版的 ivod list 一樣

如果沒有提供日期參數時，會呈現日期清單，樣式跟 default 的 table.php 差不多
可供選擇的參數是 `屆` 跟 `會期`
這一頁也參考了 ivod list 在選擇其他日期時的樣式

**Comment by ronnywang** [comment]
先說功能測試結果：
1. 左邊的選屆期我點選起來沒有反應
2. 右邊的 datatable 我希望可以取消掉，改成直接列出全部日期不分頁
像是 https://ivod.ly.gov.tw/Demand/ListCommittee/ListDate/1 一樣一次列出全部日期，這樣子我可以直接下拉或是用 Ctrl+F 找到對應日期，使用起來會比還有 pager 換頁要方便

晚點我再做更詳細 review 提供其他 coding 意見

**Comment by ronnywang** [comment]
舊版是　/ivod/datelist 為條列每日影片數，/ivod/date/2024-11-18 為列出單一日期
但現在寫法是都合併進 /collection/list/ivod/datelist 裡面了，因此失去了一個功能，就是「列出最新一天的每日影片」

請增加一個 /collection/list/ivod/datelist?日期=latest
如果日期 =latest 的話，就讓他固定顯示最新一天日期的影片，這樣就可以把 openfun.tw 首頁連到這一頁了

**Comment by typingmonk** [comment]
- 選屆與會期的 radio button 現在可以正常使用
- 右邊的 table 已把 datatable 拿掉
- 現在已支援參數 `日期=latest` 固定顯示最新一天日期的影片

**Comment by typingmonk** [comment]
#### commit 紀錄
- 現在 datelist 樣式跟 single date ivod list 樣式已從 `/views/collection/ivod_datelist.php` 拆分出來成為兩個不同的 collection_features
  - `ivod_datelist.php`: 選擇日期的列表
  - `ivod_date.php`: 日期選擇後，同一天內的 ivod 列表
- 現在 GET params 的取得與處理改寫在 `controllers/CollectionController.php` 中再 pass 給 view

**Comment by typingmonk** [comment]
已完成，麻煩 @ronnywang 做最後的確認

**Comment by ronnywang** [comment]
日期選單的「星期」是空白的
其他部份目前都 ok ，這樣把星期補上去就直接 merge 進去推上去吧

**Comment by typingmonk** [comment]
已推上線
Issue close
