### ISSUE TITLE
bill item 新增關係文書友善閱讀版

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly-v2#3]
~/collection/item/bill/{billNo}/law-diff 這一頁只顯示一個議案的對照表，不再顯示多份相關議案合併的對照表，假如這個議案沒有對照表就直接顯示「本議案暫無對照表」，並引導到查看原始的關係文書~

這張單後來的目標改為呈現關係文書的友善閱讀版
wireframe 如下：
![image](https://github.com/user-attachments/assets/b5b99a14-ee6b-4633-bcda-26bc5f3ee4be)
![image](https://github.com/user-attachments/assets/a6c0f356-d2ff-4325-a255-50b113570d27)

- 如果這個議案本身附件沒有提供關係文書：這個分頁會直接只顯示「無關係文書」
- 提案來源不是「委員提案」時：顯示提案來源欄位；不顯示提案人跟連署人欄位
- 提案來源是「委員提案」時：不顯示提案來源欄位；顯示提案人跟連署人欄位
- 如果關係文書中沒有提供法律對照表會顯示「無法律對照表」

這頁的內容盡量跟關係文書一致就好，其他想知道關聯議案、鏈結到的會議等會會在另一個 item_feature: 議案資訊中顯示（這一個 item_feature 會參考 ppg 的議案頁面），會在另一個單上處裡。

**Comment by ronnywang** [comment]
這一頁改單純一點，把他變成「關係文書」的友善閱讀版
Ex: https://ppg.ly.gov.tw/ppg/download/agenda1/02/pdf/11/01/02/LCEWA01_110102_00029.pdf

**Comment by typingmonk** [comment]
已完成「關係文書」友善閱讀版，請至測試環境確認是否符合預期

![圖片](https://github.com/user-attachments/assets/650bc27e-3b65-4b2d-9938-d9a12b858a9e)

沒有對照表的提案會這樣呈現

![圖片](https://github.com/user-attachments/assets/6fcb5340-09d7-4ea9-8d4e-eb48c61378c6)

**Comment by typingmonk** [comment]
測試 bill_no = 202110060710000 會出現錯誤
原因是這個提案並沒有「提案人」欄位，程式中並沒有妥善的處理無「提案人」欄位時的狀況

> 要養成習慣，不能假設 API 一定會給你值，所以處理一些假如 API 沒值的寫法
`$proposers = $bill->提案人;`
可以改寫成
`$proposers = $bill->提案人 ?? [];`
這樣假如 API 沒給這值就至少會是空陣列

**Comment by typingmonk** [comment]
已完成並部署到測試平台，麻煩 @ronnywang 測試
※ 這張單有改過需求，新的需求內容跟改的方向有寫在這個 issue 的第一個 comment

**Comment by typingmonk** [comment]
已完成並部署到測試平台，麻煩 @ronnywang 測試
※ 這張單有改過需求，新的需求內容跟改的方向有寫在這個 issue 的第一個 comment

**Comment by ronnywang** [comment]
好，沒問題，先把他推上線吧！

**Comment by typingmonk** [comment]
已推上正式環境
Issue closed.
